### ISSUE TITLE
Key Vault token error while saving Cosmos DB Key

### ISSUE THREAD

**Issue by angie4u** [h2floh/GeoDistributedAzureBot#16]
This is the command I used to deploy new service
```pwsh
.\Deploy\OneClickDeploy.ps1 -BOT_NAME <yourbotname> -YOUR_CERTIFICATE_EMAIL <yourmailaddressforletsencrypt> -AUTOAPPROVE $True
```
I got this error at the end of the deployment 😥

![image](https://user-images.githubusercontent.com/16282358/71614515-7b0f4d80-2bef-11ea-8992-6476f8f9c6bc.png)

**Comment by h2floh** [comment]
Hi @angie4u, 

I saw this error once before, I believe it is a temporary error within the underlying Azure CLI login token, which has to get refreshed from time to time. I just started the script again with the -RERUN option and it went just through.

`.\Deploy\OneClickDeploy.ps1 -BOT_NAME <yourbotname> -YOUR_CERTIFICATE_EMAIL <yourmailaddressforletsencrypt> -AUTOAPPROVE $True -RERUN $True`

It can also help to do a Azure CLI logout `az logout` & login again `az login`.
Can you please try again.

**Comment by angie4u** [comment]
![image](https://user-images.githubusercontent.com/16282358/71647543-fed65080-2d3b-11ea-84fc-21c525ad2dca.png)
Now it works fine! I successfully deployed using one-click deployment script! 😁
