### ISSUE TITLE
"CreateSSL.ps1" script can cause error for some subscription due to the resource provider

### ISSUE THREAD

**Issue by angie4u** [h2floh/GeoDistributedAzureBot#37]
When I try to deploy "OneClickDeployment.ps1" script under my msdn subscription, I got the following error at the certificate issuing stage. 
![image](https://user-images.githubusercontent.com/16282358/72851987-8afee680-3cf0-11ea-9969-f2a4c39c2dba.png)
It's because of my current subscription doesn't register to use "Microsoft.ContainerInstance" as a resource provider. 

* Reference: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-register-resource-provider

**[How to fix]**
![image](https://user-images.githubusercontent.com/16282358/72852129-095b8880-3cf1-11ea-8929-2aebfb8a24eb.png)

**Comment by h2floh** [comment]
Closing and pinning the issue, for easy discovery
