### ISSUE TITLE
Static bot name(mygeodistributedbot) should be changed as a parameter

### ISSUE THREAD

**Issue by angie4u** [h2floh/GeoDistributedAzureBot#7]
https://github.com/h2floh/GeoDistributedAzureBot/blob/988f59a8c5ad519fd0c56147a018990a6f8a51df/Deploy/ImportAndConnectLUIS.ps1#L35

**Comment by h2floh** [comment]
@angie4u thanks for reporting!
Should be fixed with PR #8. 
Can you pull current master and try it again?

**Comment by angie4u** [comment]
Yes I tested with updated script and it works perfectly!
Thank you for fixing this! ;)
